import hashlib
import json
from datetime import UTC, datetime
from pathlib import Path

root=Path.cwd(); out=root/'generated/wave2d/evaluator-expansion'
def load(p): return json.loads((root/p).read_text(encoding='utf-8-sig'))
def sha(p): return hashlib.sha256((root/p).read_bytes()).hexdigest()
families=[]
for name,ids,version,batch,manifest,cert in [
('dependency_supply_chain',['EMS-CTRL-003','EMS-CTRL-019','EMS-CTRL-042','EMS-CTRL-075'],'1.5','BATCH-20260814T170133.101265Z','generated/wave2d/evaluator-expansion/dependency-supply-chain-verification/verification_manifest.json','generated/wave2d/evaluator-expansion/dependency_supply_chain_registry_v1_5_certification.json'),
('test_quality',['EMS-CTRL-025','EMS-CTRL-026','EMS-CTRL-032','EMS-CTRL-060'],'1.6','BATCH-20260814T172639.027038Z','generated/wave2d/evaluator-expansion/test-quality-verification/verification_manifest.json','generated/wave2d/evaluator-expansion/test_quality_registry_v1_6_certification.json'),
('release_integrity',['EMS-CTRL-034','EMS-CTRL-035','EMS-CTRL-036','EMS-CTRL-037','EMS-CTRL-038','EMS-CTRL-040'],'1.7','BATCH-20260814T211701.004300Z','generated/wave2d/evaluator-expansion/release-integrity-verification/verification_manifest.json','generated/wave2d/evaluator-expansion/release_integrity_registry_v1_7_certification.json'),
('documentation_governance',['EMS-CTRL-002','EMS-CTRL-008','EMS-CTRL-067','EMS-CTRL-068','EMS-CTRL-069','EMS-CTRL-070','EMS-CTRL-072'],'1.8','BATCH-20260814T213844.838953Z','generated/wave2d/evaluator-expansion/documentation-governance-verification/verification_manifest.json','generated/wave2d/evaluator-expansion/documentation_governance_registry_v1_8_certification.json')]:
 c=load(cert); v=load(manifest)
 if c['promoted_control_count']!=len(ids) or v['pending_control_count']!=0: raise SystemExit(name+' evidence invalid')
 families.append({'family':name,'control_ids':ids,'control_count':len(ids),'promotion_registry_version':version,'verification_batch_id':batch,'verification_manifest_path':manifest,'verification_manifest_sha256':sha(manifest),'family_certification_path':cert,'promoted_control_count':c['promoted_control_count'],'pending_control_count':v['pending_control_count'],'verification_state':'VERIFIED_IMPLEMENTATION'})
reg='registry/wave2d_evaluator_registry_v1_8.json'; back='generated/wave2d/evaluator-expansion/priority2_remaining_implementation_backlog.json'; plan='generated/wave2d/evaluator-expansion/priority2_remaining_family_plan.json'; s=load('generated/wave2d/evaluator-expansion/priority2_remaining_summary.json')
if [s[k] for k in ('original_priority2_control_count','implemented_priority2_control_count','remaining_priority2_control_count','remaining_family_count')]!=[21,21,0,0]:raise SystemExit('backlog invalid')
m={'component':'Hayes Verify','wave':'2D','priority':2,'completion_state':'COMPLETE','generated_at_utc':datetime.now(UTC).isoformat(),'source_registry_version':'1.8','source_registry_path':reg,'source_registry_sha256':sha(reg),'original_control_count':21,'implemented_control_count':21,'remaining_control_count':0,'original_family_count':4,'completed_family_count':4,'remaining_family_count':0,'families':families}; mp=out/'priority2_completion_manifest.json';mp.write_text(json.dumps(m,indent=2))
c={'component':'Hayes Verify','phase':'Wave 2D Priority-2 Evaluator Family Expansion Completion','wave':'2D','priority':2,'certified_at_utc':datetime.now(UTC).isoformat(),'status':'PASS','completion_state':'COMPLETE','registry_version':'1.8','registry_state':'CANDIDATE_FROZEN','registry_sha256':sha(reg),'original_control_count':21,'implemented_control_count':21,'remaining_control_count':0,'original_family_count':4,'completed_family_count':4,'remaining_family_count':0,'completed_families':[x['family'] for x in families],'completion_manifest_path':str(mp.relative_to(root)).replace('\\','/'),'completion_manifest_sha256':hashlib.sha256(mp.read_bytes()).hexdigest(),'backlog_path':back,'backlog_sha256':sha(back),'family_plan_path':plan,'family_plan_sha256':sha(plan),'family_verification_references':families,'errors':[]};cp=out/'priority2_completion_certification.json';cp.write_text(json.dumps(c,indent=2));(out/'PRIORITY2_COMPLETION_SUMMARY.md').write_text('# Wave 2D Priority-2 — COMPLETE\n\n21 / 21 controls implemented; 4 / 4 families completed; 0 remaining controls; 0 remaining families.\n\nCompleted families: dependency_supply_chain, test_quality, release_integrity, documentation_governance.\n\nEvaluator implementation completion is NOT equivalent to repository compliance PASS. Repositories may legitimately produce PASS, FAIL, WARNING, INSUFFICIENT, or HUMAN_REVIEW depending on evidence and control semantics.\n')
spec={'registry_version':'1.8','registry_path':reg,'registry_sha256':sha(reg),'candidate_state':'CANDIDATE_FROZEN','documentation_governance_verification_path':'generated/wave2d/evaluator-expansion/documentation-governance-verification/verification_manifest.json','documentation_governance_verification_sha256':sha('generated/wave2d/evaluator-expansion/documentation-governance-verification/verification_manifest.json'),'priority2_completion_certification':str(cp.relative_to(root)).replace('\\','/'),'publication_branch':'feature/wave2d-evaluator-registry-v1-8-priority2-complete','commit_message':'publish Wave 2D evaluator registry v1.8 and certify Priority-2 completion','publication_prerequisites':['hash validation','Priority-2 21/21/0','family 4/4/0','Ruff','pytest','explicit staging allowlist']};(root/'registry/wave2d_evaluator_registry_v1_8_publication_spec.json').write_text(json.dumps(spec,indent=2))